import "./globals.css";
import { Inter } from "next/font/google";

export const metadata = {
  title: "GlassChain",
  description: "Generated by create next app",
};

// Include the required weights for the Poppins font
const outfit = Inter({
  subsets: ['latin'],
  weight: ['100','200','300','400','500', '600','700','800','900'], // Specify the weights you need
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        {children}
      </body>
    </html>
  );
}
